[[yq]]
arch = "aarch64"
git-tree-sha1 = "4c3fdce3265457204661a828a9c2bca2f5d84e01"
os = "macos"

    [[yq.download]]
    sha256 = "ad12caec531437d1d9ded332e4507a585077ce54674cbfb2a7227a8ac3393100"
    url = "https://github.com/JuliaBinaryWrappers/yq_jll.jl/releases/download/yq-v4.11.2+0/yq.v4.11.2.aarch64-apple-darwin.tar.gz"
[[yq]]
arch = "aarch64"
git-tree-sha1 = "a5afce3fe9501c9261c55a3db1a4d05944e3ac28"
libc = "glibc"
os = "linux"

    [[yq.download]]
    sha256 = "c968f7bf4dd6a051952a76a9f9573ec9e79891e875d727f3f00510da84fd3b64"
    url = "https://github.com/JuliaBinaryWrappers/yq_jll.jl/releases/download/yq-v4.11.2+0/yq.v4.11.2.aarch64-linux-gnu.tar.gz"
[[yq]]
arch = "aarch64"
git-tree-sha1 = "0743ed9943da40fd79205e79f3d905bcb73a4d0f"
libc = "musl"
os = "linux"

    [[yq.download]]
    sha256 = "7e8d0f3da8907b9d27f548362752bf1a4984b719f036485b1e4e031022fa17e3"
    url = "https://github.com/JuliaBinaryWrappers/yq_jll.jl/releases/download/yq-v4.11.2+0/yq.v4.11.2.aarch64-linux-musl.tar.gz"
[[yq]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "92ceb36693c34ae32951f2f909c2769d9076b82f"
libc = "glibc"
os = "linux"

    [[yq.download]]
    sha256 = "541beeef3b62176f2c565cc64da184dee1e79a3a236c58badd3798d625444c39"
    url = "https://github.com/JuliaBinaryWrappers/yq_jll.jl/releases/download/yq-v4.11.2+0/yq.v4.11.2.armv6l-linux-gnueabihf.tar.gz"
[[yq]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "c962415be9c33132f25be2a2af0f1f456eae8bfd"
libc = "musl"
os = "linux"

    [[yq.download]]
    sha256 = "aa3e2ac1f14607f10c0c3c178ed14093148a1f2367b04edf0b703b4616171173"
    url = "https://github.com/JuliaBinaryWrappers/yq_jll.jl/releases/download/yq-v4.11.2+0/yq.v4.11.2.armv6l-linux-musleabihf.tar.gz"
[[yq]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "b7bc66694417c61035c71a7f16003f12df80fa93"
libc = "glibc"
os = "linux"

    [[yq.download]]
    sha256 = "9f6b7e1160fce9f3fa9913294c6ac2713532239516798b4c3e4bfa2180c1e861"
    url = "https://github.com/JuliaBinaryWrappers/yq_jll.jl/releases/download/yq-v4.11.2+0/yq.v4.11.2.armv7l-linux-gnueabihf.tar.gz"
[[yq]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "b6099dbcde98fb2afac9a9da3bff3126ccc808cc"
libc = "musl"
os = "linux"

    [[yq.download]]
    sha256 = "b9305109ed6f6c8be3726802e18a24ac93d79fbf7002c38d6b93c34325407d9e"
    url = "https://github.com/JuliaBinaryWrappers/yq_jll.jl/releases/download/yq-v4.11.2+0/yq.v4.11.2.armv7l-linux-musleabihf.tar.gz"
[[yq]]
arch = "i686"
git-tree-sha1 = "3a6951e885b9817094bf63c940e4823b9f64e873"
libc = "glibc"
os = "linux"

    [[yq.download]]
    sha256 = "4810d621a42420e6b153f56190b8ee78308baf1fec7f6ac8b744d4a988d8938e"
    url = "https://github.com/JuliaBinaryWrappers/yq_jll.jl/releases/download/yq-v4.11.2+0/yq.v4.11.2.i686-linux-gnu.tar.gz"
[[yq]]
arch = "i686"
git-tree-sha1 = "c742e573b0a5e2761549ee05a3ee57058c270900"
libc = "musl"
os = "linux"

    [[yq.download]]
    sha256 = "7bfbd81e07bbbeed1588c6b2c205026fb196f631bae3f24c4a925a4c87e5cdeb"
    url = "https://github.com/JuliaBinaryWrappers/yq_jll.jl/releases/download/yq-v4.11.2+0/yq.v4.11.2.i686-linux-musl.tar.gz"
[[yq]]
arch = "i686"
git-tree-sha1 = "ab775286801d3f31c3d9ff655eb8dd2a95a6141d"
os = "windows"

    [[yq.download]]
    sha256 = "88f4485df230b078adadd68fd1591c0962cef874adb4792d1a6560329bc7ec6c"
    url = "https://github.com/JuliaBinaryWrappers/yq_jll.jl/releases/download/yq-v4.11.2+0/yq.v4.11.2.i686-w64-mingw32.tar.gz"
[[yq]]
arch = "powerpc64le"
git-tree-sha1 = "8cd2cf302c882eef29c25a64a359588b5d243d13"
libc = "glibc"
os = "linux"

    [[yq.download]]
    sha256 = "1a02d0b4ede840534ef75df5181b820e72566773899d541bd3839ad908eb0fc1"
    url = "https://github.com/JuliaBinaryWrappers/yq_jll.jl/releases/download/yq-v4.11.2+0/yq.v4.11.2.powerpc64le-linux-gnu.tar.gz"
[[yq]]
arch = "x86_64"
git-tree-sha1 = "d0cb7779135fa0ae5c64fe136fd2fd3f7ac4a004"
os = "macos"

    [[yq.download]]
    sha256 = "290c55c1b27a63d8433aaf79ee34de9e079c1386dca82d2479178b0b9694ad51"
    url = "https://github.com/JuliaBinaryWrappers/yq_jll.jl/releases/download/yq-v4.11.2+0/yq.v4.11.2.x86_64-apple-darwin.tar.gz"
[[yq]]
arch = "x86_64"
git-tree-sha1 = "811df22a3fc6a98c10fd7e07504d9f2c5edfbccf"
libc = "glibc"
os = "linux"

    [[yq.download]]
    sha256 = "6c7079dc4cfbef4b1e5b3334e9c24d50d5c8c13fd7146f4c78f11b47e3daef2d"
    url = "https://github.com/JuliaBinaryWrappers/yq_jll.jl/releases/download/yq-v4.11.2+0/yq.v4.11.2.x86_64-linux-gnu.tar.gz"
[[yq]]
arch = "x86_64"
git-tree-sha1 = "bcbdddc65cc5276035e602536ac452bc545eb204"
libc = "musl"
os = "linux"

    [[yq.download]]
    sha256 = "e3ba19e5130a5644264da235c87141b11fa450b87380a6db32ff26bea3ff72a4"
    url = "https://github.com/JuliaBinaryWrappers/yq_jll.jl/releases/download/yq-v4.11.2+0/yq.v4.11.2.x86_64-linux-musl.tar.gz"
[[yq]]
arch = "x86_64"
git-tree-sha1 = "e4bfa30bb9ef64318d5c99160e3027ecc932984b"
os = "freebsd"

    [[yq.download]]
    sha256 = "2c4aa6a1e94c88b60a02409b1f39198f72c82a2d61fcf200d900035a13eabcfe"
    url = "https://github.com/JuliaBinaryWrappers/yq_jll.jl/releases/download/yq-v4.11.2+0/yq.v4.11.2.x86_64-unknown-freebsd.tar.gz"
[[yq]]
arch = "x86_64"
git-tree-sha1 = "56db3a5c1879a2bede38cfda0a1281ef335d0944"
os = "windows"

    [[yq.download]]
    sha256 = "629e0dd255a526410c6692e0859f4f8841d2d833c8e5c64b8e930fbf68f5e87f"
    url = "https://github.com/JuliaBinaryWrappers/yq_jll.jl/releases/download/yq-v4.11.2+0/yq.v4.11.2.x86_64-w64-mingw32.tar.gz"
