[[yq]]
arch = "aarch64"
git-tree-sha1 = "54c70aa289d95b60474ee9c605a44b520e656232"
os = "macos"

    [[yq.download]]
    sha256 = "e663a714d7f093384ebb0888af543c8073453dde5ba10db2031a21d495846e8c"
    url = "https://github.com/JuliaBinaryWrappers/yq_jll.jl/releases/download/yq-v4.44.3+0/yq.v4.44.3.aarch64-apple-darwin.tar.gz"
[[yq]]
arch = "aarch64"
git-tree-sha1 = "5de6f1017647d274a0eb0e9bc6b89f40aa21023c"
libc = "glibc"
os = "linux"

    [[yq.download]]
    sha256 = "21d6e89fe60b9b2f59e36714a4eb829e9ac8d040fa50ca52d3731ed38389bf6e"
    url = "https://github.com/JuliaBinaryWrappers/yq_jll.jl/releases/download/yq-v4.44.3+0/yq.v4.44.3.aarch64-linux-gnu.tar.gz"
[[yq]]
arch = "aarch64"
git-tree-sha1 = "5de6f1017647d274a0eb0e9bc6b89f40aa21023c"
libc = "musl"
os = "linux"

    [[yq.download]]
    sha256 = "21d6e89fe60b9b2f59e36714a4eb829e9ac8d040fa50ca52d3731ed38389bf6e"
    url = "https://github.com/JuliaBinaryWrappers/yq_jll.jl/releases/download/yq-v4.44.3+0/yq.v4.44.3.aarch64-linux-musl.tar.gz"
[[yq]]
arch = "aarch64"
git-tree-sha1 = "66011603562c0ddcd65a95d6678d8d659f978edc"
os = "freebsd"

    [[yq.download]]
    sha256 = "b415b242e86b9e4db3fa89dd3542684419fd8b058abb11d7772b1b64d9181034"
    url = "https://github.com/JuliaBinaryWrappers/yq_jll.jl/releases/download/yq-v4.44.3+0/yq.v4.44.3.aarch64-unknown-freebsd.tar.gz"
[[yq]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "05dd7d711d62e3c7e372f6ec8d05d58b787b49cc"
libc = "glibc"
os = "linux"

    [[yq.download]]
    sha256 = "9e572e5a54eea2ecf7161bea79670297ab2558425406c8b5f6d84a3b23595e7f"
    url = "https://github.com/JuliaBinaryWrappers/yq_jll.jl/releases/download/yq-v4.44.3+0/yq.v4.44.3.armv6l-linux-gnueabihf.tar.gz"
[[yq]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "05dd7d711d62e3c7e372f6ec8d05d58b787b49cc"
libc = "musl"
os = "linux"

    [[yq.download]]
    sha256 = "9e572e5a54eea2ecf7161bea79670297ab2558425406c8b5f6d84a3b23595e7f"
    url = "https://github.com/JuliaBinaryWrappers/yq_jll.jl/releases/download/yq-v4.44.3+0/yq.v4.44.3.armv6l-linux-musleabihf.tar.gz"
[[yq]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "85ce2fae15fbb2ad25f8753f11b91d20e9d31420"
libc = "glibc"
os = "linux"

    [[yq.download]]
    sha256 = "c05ee49f7c5c401c0cd0cbb6db62fc9aa2ed98e42ad707d1cfd28fc25badf1b3"
    url = "https://github.com/JuliaBinaryWrappers/yq_jll.jl/releases/download/yq-v4.44.3+0/yq.v4.44.3.armv7l-linux-gnueabihf.tar.gz"
[[yq]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "85ce2fae15fbb2ad25f8753f11b91d20e9d31420"
libc = "musl"
os = "linux"

    [[yq.download]]
    sha256 = "c05ee49f7c5c401c0cd0cbb6db62fc9aa2ed98e42ad707d1cfd28fc25badf1b3"
    url = "https://github.com/JuliaBinaryWrappers/yq_jll.jl/releases/download/yq-v4.44.3+0/yq.v4.44.3.armv7l-linux-musleabihf.tar.gz"
[[yq]]
arch = "i686"
git-tree-sha1 = "490df0b01f781b7c1936e9c3d8fba60416ebd3a8"
libc = "glibc"
os = "linux"

    [[yq.download]]
    sha256 = "751edaf62b23f5d7953a272a0311ad1826f0c2bb6d86fa7716c6f5654216975e"
    url = "https://github.com/JuliaBinaryWrappers/yq_jll.jl/releases/download/yq-v4.44.3+0/yq.v4.44.3.i686-linux-gnu.tar.gz"
[[yq]]
arch = "i686"
git-tree-sha1 = "490df0b01f781b7c1936e9c3d8fba60416ebd3a8"
libc = "musl"
os = "linux"

    [[yq.download]]
    sha256 = "751edaf62b23f5d7953a272a0311ad1826f0c2bb6d86fa7716c6f5654216975e"
    url = "https://github.com/JuliaBinaryWrappers/yq_jll.jl/releases/download/yq-v4.44.3+0/yq.v4.44.3.i686-linux-musl.tar.gz"
[[yq]]
arch = "i686"
git-tree-sha1 = "2d475da91aaccaaeca84dda36c33ac336737c1bf"
os = "windows"

    [[yq.download]]
    sha256 = "e8502129bd60d12d8fe7cd9730ab3a73af548860a7f376c64ce4e427750665f8"
    url = "https://github.com/JuliaBinaryWrappers/yq_jll.jl/releases/download/yq-v4.44.3+0/yq.v4.44.3.i686-w64-mingw32.tar.gz"
[[yq]]
arch = "powerpc64le"
git-tree-sha1 = "907c102d37ce3ee610fd25b93a4e2d3e08beb883"
libc = "glibc"
os = "linux"

    [[yq.download]]
    sha256 = "1182a799e71e1906dd9f4ee33422143d01726b1bbedd1db53277dc001e6f8290"
    url = "https://github.com/JuliaBinaryWrappers/yq_jll.jl/releases/download/yq-v4.44.3+0/yq.v4.44.3.powerpc64le-linux-gnu.tar.gz"
[[yq]]
arch = "x86_64"
git-tree-sha1 = "662d3fcdda065a28d5a01dd30f787d466589a48d"
os = "macos"

    [[yq.download]]
    sha256 = "0fc69ef9473b83904a00386efcde4f4b7e0d59a8ea59c73d684dca631d94c3dd"
    url = "https://github.com/JuliaBinaryWrappers/yq_jll.jl/releases/download/yq-v4.44.3+0/yq.v4.44.3.x86_64-apple-darwin.tar.gz"
[[yq]]
arch = "x86_64"
git-tree-sha1 = "ce02e1291610346a18f1b2ca561323be165aa1f9"
libc = "glibc"
os = "linux"

    [[yq.download]]
    sha256 = "d6c382ab33bf48bd0cfd1f36e4fcdd02faf271e59a7a73be5dbe148910691a45"
    url = "https://github.com/JuliaBinaryWrappers/yq_jll.jl/releases/download/yq-v4.44.3+0/yq.v4.44.3.x86_64-linux-gnu.tar.gz"
[[yq]]
arch = "x86_64"
git-tree-sha1 = "b36f50a1785851f77a88fd5f7623da6c80d15003"
libc = "musl"
os = "linux"

    [[yq.download]]
    sha256 = "4b513033f4344428add9344423dba39f7f85e50c0970b522679b68348e3669b2"
    url = "https://github.com/JuliaBinaryWrappers/yq_jll.jl/releases/download/yq-v4.44.3+0/yq.v4.44.3.x86_64-linux-musl.tar.gz"
[[yq]]
arch = "x86_64"
git-tree-sha1 = "a0c3b48063fa36d9a0c3f6ab30ee44f9a32574ba"
os = "freebsd"

    [[yq.download]]
    sha256 = "4b2925871315e6ecd5d54aeb4ecdbc0278dad5f52f0845b4644c4d0dcdc280de"
    url = "https://github.com/JuliaBinaryWrappers/yq_jll.jl/releases/download/yq-v4.44.3+0/yq.v4.44.3.x86_64-unknown-freebsd.tar.gz"
[[yq]]
arch = "x86_64"
git-tree-sha1 = "c34edd57f534eb25a8cd538c7752ca79cd7514fd"
os = "windows"

    [[yq.download]]
    sha256 = "c2af9467b37e030c243238c0e16b74e2434a309a34eb28582b9a96bc8680473e"
    url = "https://github.com/JuliaBinaryWrappers/yq_jll.jl/releases/download/yq-v4.44.3+0/yq.v4.44.3.x86_64-w64-mingw32.tar.gz"
