[[yq]]
arch = "aarch64"
git-tree-sha1 = "de56b175628a659db82664f8dffcee53439927f7"
os = "macos"

    [[yq.download]]
    sha256 = "904a71c4b49332e0c66b9fe94895601cb4c8e2623177590d4f7c8c4e369e910d"
    url = "https://github.com/JuliaBinaryWrappers/yq_jll.jl/releases/download/yq-v4.42.1+0/yq.v4.42.1.aarch64-apple-darwin.tar.gz"
[[yq]]
arch = "aarch64"
git-tree-sha1 = "76fa47ac826fb5fe08de6bc9ddf5545c60e9fbc7"
libc = "glibc"
os = "linux"

    [[yq.download]]
    sha256 = "d985c8d45aa70f2eb6289de77edcdfdd8769ed6387b9926ca4f84a69a182ca47"
    url = "https://github.com/JuliaBinaryWrappers/yq_jll.jl/releases/download/yq-v4.42.1+0/yq.v4.42.1.aarch64-linux-gnu.tar.gz"
[[yq]]
arch = "aarch64"
git-tree-sha1 = "76fa47ac826fb5fe08de6bc9ddf5545c60e9fbc7"
libc = "musl"
os = "linux"

    [[yq.download]]
    sha256 = "d985c8d45aa70f2eb6289de77edcdfdd8769ed6387b9926ca4f84a69a182ca47"
    url = "https://github.com/JuliaBinaryWrappers/yq_jll.jl/releases/download/yq-v4.42.1+0/yq.v4.42.1.aarch64-linux-musl.tar.gz"
[[yq]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "92346a715081a754e7f8b7fb718eec3f6e39e521"
libc = "glibc"
os = "linux"

    [[yq.download]]
    sha256 = "11639b8b7af17152f775729dda3f5eba17914f8934a252fb724c45ece1d5b0fd"
    url = "https://github.com/JuliaBinaryWrappers/yq_jll.jl/releases/download/yq-v4.42.1+0/yq.v4.42.1.armv6l-linux-gnueabihf.tar.gz"
[[yq]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "92346a715081a754e7f8b7fb718eec3f6e39e521"
libc = "musl"
os = "linux"

    [[yq.download]]
    sha256 = "11639b8b7af17152f775729dda3f5eba17914f8934a252fb724c45ece1d5b0fd"
    url = "https://github.com/JuliaBinaryWrappers/yq_jll.jl/releases/download/yq-v4.42.1+0/yq.v4.42.1.armv6l-linux-musleabihf.tar.gz"
[[yq]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "c15c5fbda6cdfe58f1b662d72d5cb18fe0192b7c"
libc = "glibc"
os = "linux"

    [[yq.download]]
    sha256 = "a4bd87026a620124b5fd383896ee1696c002ddd15b2ff2808e6fa44640306df4"
    url = "https://github.com/JuliaBinaryWrappers/yq_jll.jl/releases/download/yq-v4.42.1+0/yq.v4.42.1.armv7l-linux-gnueabihf.tar.gz"
[[yq]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "c15c5fbda6cdfe58f1b662d72d5cb18fe0192b7c"
libc = "musl"
os = "linux"

    [[yq.download]]
    sha256 = "a4bd87026a620124b5fd383896ee1696c002ddd15b2ff2808e6fa44640306df4"
    url = "https://github.com/JuliaBinaryWrappers/yq_jll.jl/releases/download/yq-v4.42.1+0/yq.v4.42.1.armv7l-linux-musleabihf.tar.gz"
[[yq]]
arch = "i686"
git-tree-sha1 = "e187c8cd6b8f17466fd811104ff11918d58269c7"
libc = "glibc"
os = "linux"

    [[yq.download]]
    sha256 = "c7ab9801eec0d728d6eb6af0332c1edbe34a1f4b4c6d3f38ff3eea2a549dee99"
    url = "https://github.com/JuliaBinaryWrappers/yq_jll.jl/releases/download/yq-v4.42.1+0/yq.v4.42.1.i686-linux-gnu.tar.gz"
[[yq]]
arch = "i686"
git-tree-sha1 = "e187c8cd6b8f17466fd811104ff11918d58269c7"
libc = "musl"
os = "linux"

    [[yq.download]]
    sha256 = "c7ab9801eec0d728d6eb6af0332c1edbe34a1f4b4c6d3f38ff3eea2a549dee99"
    url = "https://github.com/JuliaBinaryWrappers/yq_jll.jl/releases/download/yq-v4.42.1+0/yq.v4.42.1.i686-linux-musl.tar.gz"
[[yq]]
arch = "i686"
git-tree-sha1 = "d79835f13d7b46e3bf4d412a75533730170a6402"
os = "windows"

    [[yq.download]]
    sha256 = "94b0b3a162df39c9bcc2cef9a1460a36cd9f2c70666a70ab55a7ace8b49ac01a"
    url = "https://github.com/JuliaBinaryWrappers/yq_jll.jl/releases/download/yq-v4.42.1+0/yq.v4.42.1.i686-w64-mingw32.tar.gz"
[[yq]]
arch = "powerpc64le"
git-tree-sha1 = "5e3f4ad668daad69298cd08539b7097a2f9e7f51"
libc = "glibc"
os = "linux"

    [[yq.download]]
    sha256 = "7f2524ca0fe2a6f45296b764a21f638972327d62de84a9c9cb53636091e6975b"
    url = "https://github.com/JuliaBinaryWrappers/yq_jll.jl/releases/download/yq-v4.42.1+0/yq.v4.42.1.powerpc64le-linux-gnu.tar.gz"
[[yq]]
arch = "x86_64"
git-tree-sha1 = "93765621ed07b8efd3fa1aba8f928f998bd4056d"
os = "macos"

    [[yq.download]]
    sha256 = "293c738e4292f7a43ac62af6cf72de9f5093c84033cc08559b27a77f34ddd6d7"
    url = "https://github.com/JuliaBinaryWrappers/yq_jll.jl/releases/download/yq-v4.42.1+0/yq.v4.42.1.x86_64-apple-darwin.tar.gz"
[[yq]]
arch = "x86_64"
git-tree-sha1 = "ef6043b118cc7913fcbd861e3cfdd529086b066b"
libc = "glibc"
os = "linux"

    [[yq.download]]
    sha256 = "f4796e6cb2256da48279fb29ed0d81f6a0a97a2180f5250b38fe9457d05a69ee"
    url = "https://github.com/JuliaBinaryWrappers/yq_jll.jl/releases/download/yq-v4.42.1+0/yq.v4.42.1.x86_64-linux-gnu.tar.gz"
[[yq]]
arch = "x86_64"
git-tree-sha1 = "8524e383747c62d6ef3231282e0e856c4b8c6671"
libc = "musl"
os = "linux"

    [[yq.download]]
    sha256 = "3335fd361bdc6f4fcae8ebfd328df475107f56f8765a05863f575c8ea35cb1d3"
    url = "https://github.com/JuliaBinaryWrappers/yq_jll.jl/releases/download/yq-v4.42.1+0/yq.v4.42.1.x86_64-linux-musl.tar.gz"
[[yq]]
arch = "x86_64"
git-tree-sha1 = "3de4edc1a4e7faa971600ebe8a630594a5567035"
os = "freebsd"

    [[yq.download]]
    sha256 = "4d86213141b051c9424e85046b4b26582d5447f9f2e6d90e928b99a5cf3230e3"
    url = "https://github.com/JuliaBinaryWrappers/yq_jll.jl/releases/download/yq-v4.42.1+0/yq.v4.42.1.x86_64-unknown-freebsd.tar.gz"
[[yq]]
arch = "x86_64"
git-tree-sha1 = "511e0747680510c8f98a35728392cc704f330554"
os = "windows"

    [[yq.download]]
    sha256 = "e15a24b6aeb45f383a706a10f7cb810c7a8376ee864320dddaab2b99498a67c5"
    url = "https://github.com/JuliaBinaryWrappers/yq_jll.jl/releases/download/yq-v4.42.1+0/yq.v4.42.1.x86_64-w64-mingw32.tar.gz"
