[[yq]]
arch = "aarch64"
git-tree-sha1 = "d76fd683f3fcea0c2beef0d7f5cb5602dfeedd5c"
os = "macos"

    [[yq.download]]
    sha256 = "da9755f15275367b0ed8a35d252bc99216f3c7d51bc34987c68cb161a981f5d4"
    url = "https://github.com/JuliaBinaryWrappers/yq_jll.jl/releases/download/yq-v4.19.1+0/yq.v4.19.1.aarch64-apple-darwin.tar.gz"
[[yq]]
arch = "aarch64"
git-tree-sha1 = "32d7f6cd55b55650c3206ca7f9bc080b6ac6072f"
libc = "glibc"
os = "linux"

    [[yq.download]]
    sha256 = "ecd68d52ea62f7024a877a223f1b9c2e7e8e1d4121153fce8ce131aa3f3e45cc"
    url = "https://github.com/JuliaBinaryWrappers/yq_jll.jl/releases/download/yq-v4.19.1+0/yq.v4.19.1.aarch64-linux-gnu.tar.gz"
[[yq]]
arch = "aarch64"
git-tree-sha1 = "30a44e573e3f3aef0fb33cb30b33c4389f3db57c"
libc = "musl"
os = "linux"

    [[yq.download]]
    sha256 = "27cf6f6d240b39b8cbfabdb5bbc622ed3c5efa1e3a23b2098b3d2f0741cd46fd"
    url = "https://github.com/JuliaBinaryWrappers/yq_jll.jl/releases/download/yq-v4.19.1+0/yq.v4.19.1.aarch64-linux-musl.tar.gz"
[[yq]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "203ca97baf9f896885d3f2ead6e8de6a889bb131"
libc = "glibc"
os = "linux"

    [[yq.download]]
    sha256 = "febf31bd3fd899fc1fd221a535ed13034a372375a25540dd8527eaf11d360b78"
    url = "https://github.com/JuliaBinaryWrappers/yq_jll.jl/releases/download/yq-v4.19.1+0/yq.v4.19.1.armv6l-linux-gnueabihf.tar.gz"
[[yq]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "bf8b287e0faf695b07e472624449b14fe434b9a4"
libc = "musl"
os = "linux"

    [[yq.download]]
    sha256 = "84de1f5b4984a2759f22f1eba120e68bd33ca5b506837f8184ae68ef9d8fc8d4"
    url = "https://github.com/JuliaBinaryWrappers/yq_jll.jl/releases/download/yq-v4.19.1+0/yq.v4.19.1.armv6l-linux-musleabihf.tar.gz"
[[yq]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "c70ddf70030fd98b460f7f5f2408ca458e840838"
libc = "glibc"
os = "linux"

    [[yq.download]]
    sha256 = "b687ba831af885f395e879fc83e033dee014abc558202d5999866ea83020be7a"
    url = "https://github.com/JuliaBinaryWrappers/yq_jll.jl/releases/download/yq-v4.19.1+0/yq.v4.19.1.armv7l-linux-gnueabihf.tar.gz"
[[yq]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "eb12f71571526b8baca2174db5e1e62d44ef67e2"
libc = "musl"
os = "linux"

    [[yq.download]]
    sha256 = "b56fe68382073ba607b15283aa364007d1b56e6eaa6e33d4f987bf62eff4103d"
    url = "https://github.com/JuliaBinaryWrappers/yq_jll.jl/releases/download/yq-v4.19.1+0/yq.v4.19.1.armv7l-linux-musleabihf.tar.gz"
[[yq]]
arch = "i686"
git-tree-sha1 = "6e91dfa846bc7b0fe4b7122e803807ffc0f385cf"
libc = "glibc"
os = "linux"

    [[yq.download]]
    sha256 = "e59efcee4d353b5a00ca41d868b733359b48d92c0c589cb7b58f64502002da67"
    url = "https://github.com/JuliaBinaryWrappers/yq_jll.jl/releases/download/yq-v4.19.1+0/yq.v4.19.1.i686-linux-gnu.tar.gz"
[[yq]]
arch = "i686"
git-tree-sha1 = "2f11d4bb32fe62414769133ab81d50b5ec1d522c"
libc = "musl"
os = "linux"

    [[yq.download]]
    sha256 = "4dc1c0bbc874506b881b8b6fac903bc8237842a8bd8121914d04a36951d988bf"
    url = "https://github.com/JuliaBinaryWrappers/yq_jll.jl/releases/download/yq-v4.19.1+0/yq.v4.19.1.i686-linux-musl.tar.gz"
[[yq]]
arch = "i686"
git-tree-sha1 = "922d93747ba060dafcb5161045d53b81ad0bb4aa"
os = "windows"

    [[yq.download]]
    sha256 = "66801e0f6c6e64e5186e4924b815423cac6e222f2a16b8078a142ac05ad3be7a"
    url = "https://github.com/JuliaBinaryWrappers/yq_jll.jl/releases/download/yq-v4.19.1+0/yq.v4.19.1.i686-w64-mingw32.tar.gz"
[[yq]]
arch = "powerpc64le"
git-tree-sha1 = "fb988da0dab35aa5a91ce777492677df83ae0efc"
libc = "glibc"
os = "linux"

    [[yq.download]]
    sha256 = "4ea18ee87aae0426d5f26ffb200d469dc9d9b43d0f9940a89f718f5e7641b19a"
    url = "https://github.com/JuliaBinaryWrappers/yq_jll.jl/releases/download/yq-v4.19.1+0/yq.v4.19.1.powerpc64le-linux-gnu.tar.gz"
[[yq]]
arch = "x86_64"
git-tree-sha1 = "1df696c09fc66ca12c0ca68ceca0629a0d616e17"
os = "macos"

    [[yq.download]]
    sha256 = "8bbcef1e4c711cd4089ff8d7ea2b33fcf1744488c3d7762dac3f586391946aeb"
    url = "https://github.com/JuliaBinaryWrappers/yq_jll.jl/releases/download/yq-v4.19.1+0/yq.v4.19.1.x86_64-apple-darwin.tar.gz"
[[yq]]
arch = "x86_64"
git-tree-sha1 = "e30fea286486febe3dec87aa7397f02af8bce5eb"
libc = "glibc"
os = "linux"

    [[yq.download]]
    sha256 = "76e2fbe7d6a5c3642f653fb3ed26f371daec7227a20c33cc1b782173de5e7b1b"
    url = "https://github.com/JuliaBinaryWrappers/yq_jll.jl/releases/download/yq-v4.19.1+0/yq.v4.19.1.x86_64-linux-gnu.tar.gz"
[[yq]]
arch = "x86_64"
git-tree-sha1 = "e4527b09ddddfdecb7580694c1b978daf4740702"
libc = "musl"
os = "linux"

    [[yq.download]]
    sha256 = "eba58d396cb619709bf7e8641d012a66c2254a0a0be474fbc2ea58892d914b72"
    url = "https://github.com/JuliaBinaryWrappers/yq_jll.jl/releases/download/yq-v4.19.1+0/yq.v4.19.1.x86_64-linux-musl.tar.gz"
[[yq]]
arch = "x86_64"
git-tree-sha1 = "c1ae828e0b463a67b777ff449ead443cef12660c"
os = "freebsd"

    [[yq.download]]
    sha256 = "6f09d29bc5570ccf7638b89265f383b10e0a9b0116dbe3a3c66550f5ecb59973"
    url = "https://github.com/JuliaBinaryWrappers/yq_jll.jl/releases/download/yq-v4.19.1+0/yq.v4.19.1.x86_64-unknown-freebsd.tar.gz"
[[yq]]
arch = "x86_64"
git-tree-sha1 = "381249b908c48ff0ec7b4a5103ccc4112969b0dc"
os = "windows"

    [[yq.download]]
    sha256 = "e9d538530471fdc7841db68272d15f677c8af19dc0a89d94c60335c7595f7fd2"
    url = "https://github.com/JuliaBinaryWrappers/yq_jll.jl/releases/download/yq-v4.19.1+0/yq.v4.19.1.x86_64-w64-mingw32.tar.gz"
